### ISSUE TITLE
When moving card to new column, it changes notebooks

### ISSUE THREAD

**Issue by BenoitJGirard** [benlau/joplin-plugin-kanmug#4]
If note is in a sub-notebook, and its card is moved to a different column, the note is moved to the root notebook.

This seems to be undocumented, unwanted behavior.

**Comment by benlau** [comment]
Let's clarify the issue.  

Assume you have this Kanban:  

```yaml
```kanban
filters:
  rootNotebookPath: /
  tag: issue4
columns:
  - name: Backlog
    backlog: true
  - name: Column1
    notebookPath: /column1
  - name: Column2
    tag: column2
```

Moving a note from Column1 to Column2 will move the note to the root folder.  

Is that your problem?  

To fulfill the rule, the program can only move the note out of the `/column1` folder. I understand that moving it to the root folder is not ideal, but it is difficult to think of an alternative. (P.S. This was the original behavior before forking the project.)  

What if I change the behaviour to:

1. Move to the first folder which is not `column1` 
2. And then show a warning to tell where does it moved.

What do you think?
